### ISSUE TITLE
Found no static mods

### ISSUE THREAD

**Issue by lonelu** [yeastrc/proxl-import-metamorpheus#1]
Hi, I used the newest version of MetaMorpheus (v277) to generate pep.xml and tried to use metamorphe2ProxlXML.jar to convert it to .proxl.xml. 
The result showed " Finding static mods...Done. Found no static mods". No error reported.
Then When I uploaded the data to the web of proXL, the uploading failed with the following message: 
"The content of element 'static_modifications' is not complete. One of '{static_modification}' is expected.] "
I deleted "<static_modifications/>" from the output .proxl.xml file. Then everything worked. I really love the fancy figures from the web of proXL!!! 
I am not sure what static mod mean. This maybe a bug of MetaMorpheus or proXL. Thanks.

**Comment by mriffle** [comment]
Hi lonelu,

Thanks for the bug report. I'm so glad you like proxl! If you have any suggestions, feature requests, or comments, please don't hesitate to let me know.

A couple of things are going on here, one is a bug I'll fix in the MetaMorpheus proxl XML converter. 

1. A static mod is what proxl calls a fixed mod. I wrote this converter such that it'll work correctly once the reporting of the positions of mods in the MetaMorpheus output reports the first residue in the peptide as position 1 for all the mods. Until then, the reported modified residue will be off in proxl by 1--and it won't find any static/fixed mods.

2. I have a bug in the converter that reports an empty <static_mods> section if no static mods are found. 

I will update the converter to fix this, create a new release, and leave a comment here once that's done.

**Comment by mriffle** [comment]
OK, the issue related to outputting an empty <static_mods> section is now fixed and tested for the latest release.

**Comment by lonelu** [comment]
Thanks for the quick reply. It works now. 
This is the best tool for MetaMorpheus crosslink as far as I know.  I will let you know if I have new features I want to add.
